
CREATE SCHEMA IF NOT EXISTS demo;
CREATE TABLE demo.users (
   id SERIAL PRIMARY KEY,
   firstName VARCHAR ( 50 ) NOT NULL,
   lastName VARCHAR ( 50 ) NOT NULL,
   email VARCHAR ( 255 ) UNIQUE NOT NULL
);


