apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: quay.io/jpetnik/multi-arch/backend:v1
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DATABASE_PASSWORD
            - name: GREETING_HOST
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: GREETING_HOST
            - name: GREETING_PORT
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: GREETING_PORT
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
